@SimpleStore.IdentityServer_HostAddress = http://localhost:5081

GET {{SimpleStore.IdentityServer_HostAddress}}/health/
Accept: application/json

###

POST {{SimpleStore.IdentityServer_HostAddress}}/register
Accept: application/json
Content-Type: application/json
{
  "username": "loyd17",
  "email": "example@gmail.com",
  "password": "Test@1234"
}

###

POST {{SimpleStore.IdentityServer_HostAddress}}/login
Content-Type: application/json
{
  "login": "example@gmail.com",
  "password": "Test@1234"
}

###

POST {{SimpleStore.IdentityServer_HostAddress}}/refresh-token
Content-Type: application/json
{
  "guid": "6538ECD5-735A-40BC-6A8E-08DE2B99DD27",
  "refreshtoken": "QNzTEg2p1AZP5rthntWSjPUR7U21EpnUVCEjGnqzF0I="
}

###